Update rule_engine.js
此版本解決了：

require is not defined

does not provide an export named 'default'

SyntaxError: Unexpected identifier 'assert'